In [43]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

1. Sudoki solving  
her row ka sum 45 hota hai 
her col ka sum 45 hota hai

In [2]:
s.sum()
sum(s)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [42]:

# Check row sums valid and uniqueness
row_sums = np.sum(s, axis=1)

for idx in range(9):
    row = s[idx]
    row_sum = row_sums[idx]

    if row_sum != 45:
        print(f'Row sum invalid at index {idx} with value {row_sum}')
        break
 
    if len(set(row)) != 9:
        print(f'Duplicate found in row {idx}')
        break
else:
    print('All row sums are valid and all rows have unique numbers')

# Check column sums valid  and uniqueness
col_sums = np.sum(s, axis=0)  

for idx in range(9):
    col = s[:, idx]   
    col_sum = col_sums[idx]
    
    if col_sum != 45:
        print(f'Column sum invalid at index {idx} with sum {col_sum}')
        break
    if len(set(col)) != 9:
        print(f'Duplicate found in column {idx}')
        break
else:
    print('All column sums are valid and all columns have unique numbers')

Row sum invalid at index 3 with value 44
Column sum invalid at index 2 with sum 44


In [ ]:
# row ka sum dekho  ye hr row ka sum nikalega 
row_sum = np.sum(s, axis=1)

# hr row ka mila hua sum ko check 
for idx, sum_value in enumerate(row_sum):
    if sum_value != 45:
        print(f'row sum invalid at index {idx} with value {sum_value}')
        break
else:
    print('all rows sum are valid')


row sum invalid at index 0 with value 46


In [29]:
# Check column sums
col_sums = np.sum(s, axis=0)  # Sum along axis 0 for column sums

for idx, col_sum in enumerate(col_sums):
    if col_sum != 45:
        print(f'Column sum invalid at index {idx} with sum {col_sum}')
        break
else:
    print('All column sums valid')


Column sum invalid at index 1 with sum 46


In [5]:
#grid accessing 
s[0:3, 0:3]

s[0:3, 3:6]

s[0:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [19]:
#ab pura grid ko loop ke through access krna 
print(s)
for i in range(0,9,3):
    for j in range(0,9,3):

        # ek ek grid ko lena
        n = s[i:i+3, j:j+3]
        grid_sum = n.sum()
        
        # Check  grid contains valid no.  (1-9)
        valid_numbers = all((1 <= x <= 9) for x in n.flatten())
        
        # Check if numbers are unique in the grid
        unique_numbers = len(set(n.flatten())) == 9
        
        # Check if sum equals 45 
        valid_sum = grid_sum == 45
        
        print(f"Grid at position ({i//3}, {j//3}):")
        print(n)
        print(f"Sum: {grid_sum}")
        
        # Print validation results
        valid_numbers_text = "Yes" if valid_numbers else "No"
        unique_numbers_text = "Yes" if unique_numbers else "No"
        valid_sum_text = "Yes" if valid_sum else "No"
        grid_valid_text = "Yes" if (valid_numbers and unique_numbers and valid_sum) else "No"
        
        print(f"Valid numbers (1-9): {valid_numbers_text}")
        print(f"All numbers unique: {unique_numbers_text}")
        print(f"Sum equals 45: {valid_sum_text}")
        print(f"Grid is valid: {grid_valid_text}\n")


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]]
Grid at position (0, 0):
[[5 3 4]
 [6 7 2]
 [1 9 8]]
Sum: 45
Valid numbers (1-9): Yes
All numbers unique: Yes
Sum equals 45: Yes
Grid is valid: Yes

Grid at position (0, 1):
[[6 7 8]
 [1 9 5]
 [3 4 2]]
Sum: 45
Valid numbers (1-9): Yes
All numbers unique: Yes
Sum equals 45: Yes
Grid is valid: Yes

Grid at position (0, 2):
[[9 1 2]
 [3 4 8]
 [5 6 7]]
Sum: 45
Valid numbers (1-9): Yes
All numbers unique: Yes
Sum equals 45: Yes
Grid is valid: Yes

Grid at position (1, 0):
[[5 3 4]
 [6 7 2]
 [1 9 8]]
Sum: 45
Valid numbers (1-9): Yes
All numbers unique: Yes
Sum equals 45: Yes
Grid is valid: Yes

Grid at position (1, 1):
[[6 7 8]
 [1 9 5]
 [3 4 2]]
Sum: 45
Valid numbers (1-9): Yes
All numbers unique: Yes
Sum equals 45: Yes
Grid is valid: Yes

Grid at position (1, 2):
[[9 1 2]
 [3 4 8]
 [5 6 7]]
Sum: 45
Vali

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
])

In [ ]:
import numpy as np

def check_sudoku(grid):
    numbers = set([1,2,3,4,5,6,7,8,9])
    
    # Look at each row
    for row in range(9):
        if set(grid[row, :]) != numbers:
            print(f"Row {row+1} has wrong numbers: {grid[row, :]}")
            return False
            
    # Look at each column    
    for col in range(9):
        if set(grid[:, col]) != numbers:
            print(f"Column {col+1} has wrong numbers: {grid[:, col]}")
            return False
    
    # Look at each 3x3 box
    for box_row in [0,3,6]:
        for box_col in [0,3,6]:
            # Get numbers in current box
            box = grid[box_row:box_row+3, box_col:box_col+3]
            box_numbers = set(box.flatten())
            
            if box_numbers != numbers:
                print(f"Box at position ({box_row//3},{box_col//3}) has wrong numbers: {box.flatten()}")
                return False
                
    return True

# Check if solution is valid
if check_sudoku(s):
    print("✅ Correct! Valid Sudoku solution!")
else:
    print("❌ Wrong! Not a valid solution.")


In [7]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [8]:
#Get the shape of the matrix.

data.shape

(5, 3)

In [9]:
# avg mark  
np.mean(data[:, 0])

18.4

In [10]:
# avg math mark 
data[: , 1]

array([85, 92, 76, 65, 90])

In [11]:
# avg hgihest mark 

np.max(data[:,2])

95

In [12]:
#set details of the student who scored more than 90 marks
data[data[:, 1] > 90]


array([[19, 92, 88]])

In [13]:
#increment math marks of all students by 5 

data[:,1]+=5
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [14]:
data[:,0]<=19 # boolean value return krega 
len(data[data[:,0]<=19])

4

In [15]:
#calculate the average marks in each sub column wisee means 

np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [16]:
# get who scored atleast 80 in bot hsub 

data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [17]:
#replace al science mark <75 with 0 
data[:,2][data[:,2] < 80] = 0
data

array([[18, 90,  0],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])