import numpy as np 

In [1]:
import numpy as np 

import pandas as pd 
import seaborn as sns 

import matplotlib.pyplot as plt 
import warnings 

warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df.drop(['deck', 'embark_town',  'class' , 'who', 'adult_male','alive'], axis=1, inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [7]:
# means avg value daal do 
df['age'].fillna(df['age'].mean(), inplace=True) 

In [8]:
df.dropna(subset=['embarked'], axis=0, inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [10]:
# need label encoding  

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [11]:
df.head()


survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [12]:
df['sex']

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 889, dtype: object

In [13]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [14]:
df.astype('int').dtypes

survived    int32
pclass      int32
sex         int32
age         int32
sibsp       int32
parch       int32
fare        int32
embarked    int32
alone       int32
dtype: object

# logistic regression model

In [15]:
x = df.drop('survived', axis=1)
y = df['survived']

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression
# logistic regression model
model = LogisticRegression()


model.fit(X_train, y_train)

LogisticRegression()

In [18]:
y_pred = model.predict(X_test)

In [19]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [20]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [22]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [23]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]], dtype=int64)

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [26]:
df

survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2  False
1           1       1    0  38.000000      1      0  71.2833         0  False
2           1       3    0  26.000000      0      0   7.9250         2   True
3           1       1    0  35.000000      1      0  53.1000         2  False
4           0       3    1  35.000000      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2   True
887         1       1    0  19.000000      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  26.000000      0      0  30.0000         0   True
890         0       3    1  32.000000      0      0   7.7500         1   True

[889 rows x 9 columns]

In [27]:
X_train_scaled  = scaler.fit_transform(X_train)

In [28]:
X_train_scaled 

array([[-1.58410418, -1.40530972, -0.59963554, ...,  2.43059683,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.01249955, ..., -0.35813533,
        -1.95246446, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.16296612, ..., -0.49094895,
         0.58770431,  0.81076671],
       ...,
       [-1.58410418, -1.40530972,  1.38312878, ..., -0.12471679,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.67589571, ...,  0.04708333,
         0.58770431, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.23922629, ..., -0.47611594,
         0.58770431,  0.81076671]])

In [29]:
X_test_scaled = scaler.transform(X_test)

X_test_scaled

array([[ 0.8122747 ,  0.71158691, -0.14207455, ..., -0.49238913,
         0.58770431,  0.81076671],
       [-1.58410418, -1.40530972, -1.20971688, ...,  1.78882298,
         0.58770431, -1.23340042],
       [ 0.8122747 , -1.40530972, -1.20971688, ..., -0.42348235,
        -1.95246446, -1.23340042],
       ...,
       [ 0.8122747 , -1.40530972,  0.62052712, ..., -0.01368686,
         0.58770431, -1.23340042],
       [ 0.8122747 , -1.40530972,  0.23922629, ..., -0.32974268,
         0.58770431, -1.23340042],
       [ 0.8122747 , -1.40530972, -1.97231854, ..., -0.31245242,
         0.58770431, -1.23340042]])

# logistic regression model

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [31]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

# yaha y_train ko scale nhi kiye qki ye 0 / 1 me ana chahiye 

KNeighborsClassifier()

In [32]:
y_prediction_knn = knn_model.predict(X_test_scaled)

In [33]:
accuracy_score(y_test, y_prediction_knn)

0.797752808988764

In [34]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]], dtype=int64)

In [35]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



standard scaling ka use krte ; 

started with site

# naiv bayes : 
 isme standard scalling ki jarurat nhi hoti qki scatter data ke sath work kr rhe hote hai

In [36]:
X_test

pclass  sex   age  sibsp  parch      fare  embarked  alone
281       3    1  28.0      0      0    7.8542         2   True
435       1    0  14.0      1      2  120.0000         2  False
39        3    0  14.0      1      0   11.2417         0  False
418       2    1  30.0      0      0   13.0000         2   True
585       1    0  18.0      0      2   79.6500         2  False
..      ...  ...   ...    ...    ...       ...       ...    ...
433       3    1  17.0      0      0    7.1250         2   True
807       3    0  18.0      0      0    7.7750         2   True
25        3    0  38.0      1      5   31.3875         2  False
85        3    0  33.0      3      0   15.8500         2  False
10        3    0   4.0      1      1   16.7000         2  False

[178 rows x 8 columns]

In [37]:
X_train

pclass  sex        age  sibsp  parch      fare  embarked  alone
708       1    0  22.000000      0      0  151.5500         2   True
240       3    0  29.699118      1      0   14.4542         0  False
382       3    1  32.000000      0      0    7.9250         2   True
792       3    0  29.699118      8      2   69.5500         2  False
683       3    1  14.000000      5      2   46.9000         2  False
..      ...  ...        ...    ...    ...       ...       ...    ...
107       3    1  29.699118      0      0    7.7750         2   True
271       3    1  25.000000      0      0    0.0000         2   True
862       1    0  48.000000      0      0   25.9292         2   True
436       3    0  21.000000      2      2   34.3750         2  False
103       3    1  33.000000      0      0    8.6542         2   True

[711 rows x 8 columns]

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
model_NB = GaussianNB()


In [40]:
model_NB.fit(X_train, y_train)

GaussianNB()

In [41]:
y_pred_NB = model_NB.predict(X_test)
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [42]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [43]:
accuracy_score(y_test, y_pred_NB)

0.7752808988764045

In [44]:
confusion_matrix(y_test, y_pred_NB)

array([[84, 25],
       [15, 54]], dtype=int64)

In [45]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



# Decession Tree

In [46]:
from sklearn.tree import DecisionTreeClassifier


In [47]:
model_DT = DecisionTreeClassifier( random_state=42  )
model_DT.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [48]:
model_DT.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [49]:
y_pred_DT = model_DT.predict(X_test_scaled)

In [50]:
y_pred_DT

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1], dtype=int64)

In [51]:
accuracy_score(y_test, y_pred_DT)

0.7415730337078652

In [52]:
confusion_matrix(y_test, y_pred_DT)

array([[80, 29],
       [17, 52]], dtype=int64)

'              precision    recall  f1-score   support\n\n           0       0.82      0.73      0.78       109\n           1       0.64      0.75      0.69        69\n\n    accuracy                           0.74       178\n   macro avg       0.73      0.74      0.74       178\nweighted avg       0.75      0.74      0.74       178\n'

In [55]:
classification_report(y_test, y_pred_DT)

'              precision    recall  f1-score   support\n\n           0       0.82      0.73      0.78       109\n           1       0.64      0.75      0.69        69\n\n    accuracy                           0.74       178\n   macro avg       0.73      0.74      0.74       178\nweighted avg       0.75      0.74      0.74       178\n'

**SVM Model**

In [56]:
from sklearn.svm import SVC

chuki data 3d dimensional me hai to aise me distribution krne ke liye rbf ka use krte ye 3d axeses me differenciate krne me help krta


yaha rbf ek   kernal hota  hai bahut saare kernel hote hai 

In [58]:
model_svm = SVC(kernel="rbf")

In [59]:
model_svm.fit(X_train_scaled, y_train)

SVC()

In [61]:
y_pred_svc = model_svm.predict(X_test_scaled)

In [62]:
accuracy_score(y_test, y_pred_svc)

0.8146067415730337

In [64]:
confusion_matrix(y_test, y_pred_svc)

array([[91, 18],
       [15, 54]], dtype=int64)

In [65]:
print(classification_report(y_test, y_pred_svc))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       109
           1       0.75      0.78      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178

