pythos has large mathematically powerful library called numpy
but pythojn ke paas array nhi tha 
isliye num array develop hua hai

numpy c me likha gya hai aur isko library ke form me python me itegrate ho jata 
iska computationally power jayada hota hai 50 times faster than python list 


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a = [1,2,3,4,5 , "hello"]

np.array(a) # isme multiple data type hai leking array same data type elemtn rkhta 

b = [1,2,3,4,5,6]
np.array(b) # isme sare elemnt int hai  

array([1, 2, 3, 4, 5, 6])

In [10]:
arr= np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

 isme diya hua range ko  utna part me devide kr dega   chahe float me krke q n kr de 

In [23]:
# isme diya hua range ko  utna part me devide kr dega 
arr = np.linspace(1,10,4) 
arr


array([ 1.,  4.,  7., 10.])

# RANDOM GENERATION FUCNTION 

In [29]:
# ye normalization me hota means 0-1 ke bich value aayega 
np.random.rand(10)

array([0.91174262, 0.82330512, 0.61568219, 0.73975031, 0.1031583 ,
       0.96316612, 0.42325685, 0.10224721, 0.36246457, 0.40331071])

In [33]:
# standardizaiton  means -3 -> 3 tk value ajayega 

np.random.randn(10)

array([ 0.10157276, -0.91179967,  2.10755867, -1.25203403, -1.61049596,
       -0.8361277 ,  1.90793515, -2.238919  ,  0.19142883, -0.58669988])

In [39]:
np.random.randint(10,20,13)

array([19, 12, 12, 18, 19, 12, 19, 19, 14, 13, 13, 15, 17], dtype=int32)

# array atributes 
isme fucntion likhne ki jarurat nhi hot i   


In [43]:
arr = np.array([[1,2,3,4,5] , [1,2,3,4,5]])

arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [46]:
arr.shape

(2, 5)

In [48]:
arr.dtype

dtype('int64')

# ARRAY METHODS

In [51]:
arr.min()

np.int64(1)

In [52]:
arr.max()

np.int64(5)

In [55]:
arr.sum()

np.int64(30)

In [57]:
# row and column wise 
arr   


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [60]:
np.sum(arr, axis=1)


array([15, 15])

In [63]:
arr.mean()

np.float64(3.0)

In [66]:
arr.argmin()
arr.argmax()

np.int64(4)

Reshaping and Resizing 

In [70]:
arr = np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
arr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# NUMPY indexing and Slicing 

In [73]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
arr[1:5:2]

array([12, 14])

In [3]:
arr = np.arange(1,31)
arr

NameError: name 'np' is not defined

In [83]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [90]:
arr[1:4,2:6:2]

array([[ 9, 11],
       [15, 17],
       [21, 23]])

In [98]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [1]:
arr = arr[bool_index]
arr

NameError: name 'arr' is not defined

# Array operations 


In [108]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2

array([ 7,  9, 11, 13, 15])

# Broadcasting 


In [ ]:
l = [ 10,20,30,40]
arr = np.array(l)
# l +10   # not possible  iske liye for loop lga ke krke list me covert krnahoga  to iske liye hum 
arr + 10 # ye asani se kr deta 

arr


array([10, 20, 30, 40])

# DEEP AND SHALLOW COPY 


isme numpy me dekhenge to shallow copy bnata hai means jb bhi slicing krke  koiportion me mathematical operation perform krte to wo usi portion me perfrom hoga n ki original me ye us oportion ka ram me alg se space bna leta
iski jaga list me kre ya other data strucutre to isme hoga 

In [119]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [122]:
slice = a[:5]
slice *10

slice 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# MATRIX OPERAITON 

In [125]:
a = np.array([[2,1] , [3,4]])
b = np.array([[2,1] , [3,4]])
a*b

array([[ 4,  1],
       [ 9, 16]])

In [126]:
a.T

array([[2, 3],
       [1, 4]])


# Advanced array manipulation 

Stacking array  : 2 array ko jod dena 

In [130]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
c = np.array([4,5,6,7])

# 2d array wise stack bna leta 
np.vstack((a,b,c))



array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [134]:
# horizontal wise stack 
np.hstack((a,b))  

array([1, 2, 3, 4, 4, 5, 6, 7])

In [135]:
np.column_stack((a,b))  

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

 spliting array  : array ko multiple part me split krna 

In [145]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [149]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [150]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]